[book]
title = "A.eins"
authors = []
language = "de"

[output.html]
additional-css = ["custom.css"]
no-section-label = true
site-url = "/hilfe/"

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = true

# using mdbook-pandoc
#[output.pandoc.profile.pdf]
#output-file = "output.pdf"
#to = "latex"
#number-sections = false

# using mdbook-pdf
[output.pdf]


[preprocessor.gitinfo]
enable = true

# choose placement(s)
header = false   # default: false
footer = true    # default: true

# common formatting
font-size   = "0.9em"
separator   = " • "
date-format = "%Y-%m-%d"
time-format = "%H:%M:%S"
branch      = "main"
hyperlink   = true  # make hash/branch clickable when possible

# optional timezone handling
timezone = "local"   # "local" (default) | "utc" | "source" | "fixed:+02:00"

[preprocessor.gitinfo.message]
footer = "Stand {{date}}{{sep}}commit: {{hash}}"