name: Deploy A.eins Hilfe

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2
      - name: Add mdbook to path
        run: echo "/opt/cargo/bin" >> $GITHUB_PATH
      - name: Run tests
        run: mdbook test
      - name: Build Hilfe
        run: mdbook build
      # TODO - need something to upload generated pdf for distribution
      # following is a naive happy path approach
      # for production a better check is mandatory!
      - name: Remove old container
        run: |
          docker stop spike-a1hilfe-mdbook
          docker rm spike-a1hilfe-mdbook
      - name: Build Docker image
        run: docker build -t spike-a1hilfe-mdbook:latest .
      - name: Deploy Onlinehilfe
        run: >
          docker run -d
          --restart always
          --name spike-a1hilfe-mdbook
          -p 8181:80
          spike-a1hilfe-mdbook:latest
        