name: Deploy A.eins Hilfe

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.prettierignore'

  workflow_dispatch:

jobs:
  build:
    runs-on: spike-a1hilfe-mdbook
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2
      - name: Add mdbook and extensions to path
        run: echo "/opt/cargo/bin" >> $GITHUB_PATH
      - name: Prepare correct book.toml for build
        run: mv book.prod.toml book.toml
      # - name: Run tests
      #   run: mdbook test
      - name: Build Hilfe
        run: mdbook build
      # # this is for a workaround
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: v24
      # # Chrome / Chromium's printToPdf is the limiting factor
      # # because the size of the print.html is just too big to convert to in one run 
      # - name: Custom PDF generation!
      #   run: |
      #     cd pdf_pipeline
      #     npm i
      #     npm run build
      # - name: Get short commit SHA and store it
      #   run: echo "CID=$(git log -1 --format=%h)" >> $GITHUB_ENV
      # - name: Rename PDF file
      #   run: |
      #     cp book/pdf/output.pdf book/pdf/Aeins-$CID.pdf
      #     mv book/pdf/output.pdf book/pdf/Aeins.pdf
      # - name: Copy PDF to LFB
      #   run: sshpass -p '${{ secrets.SCP_PW }}' scp book/pdf/Aeins-$CID.pdf '${{ secrets.SCP_USER }}@${{ vars.SCP_HOST }}:${{ vars.SCP_DIR }}'
      # - name: Remove pdf and _parts folder
      #   run: |
      #     rm -r book/pdf
      #     rm -r book/_parts
      # - name: Handle old container
      #   run: |
      #     chmod +x ./handle-old-container.sh
      #     ./handle-old-container.sh spike-a1hilfe-mdbook      
      # - name: Build Docker image
      #   run: docker build -t spike-a1hilfe-mdbook:latest .
      # - name: Deploy internal Onlinehilfe
      #   run: >
      #     docker run -d
      #     --restart always
      #     --name spike-a1hilfe-mdbook
      #     --network dev
      #     -p 8181:80
      #     spike-a1hilfe-mdbook:latest
      # - name: Upload to amic.de/hilfe
      #   uses: joutvhu/ftp-transfer@v1
      #   with:
      #     host: ${{ vars.FTP_HOST }}
      #     port: ${{ vars.FTP_PORT }}
      #     username: ${{ secrets.FTP_USER }}
      #     password: ${{ secrets.FTP_PW }}
      #     commands: |
      #       delete /wordpress_2025/hilfe/book
      #       put ./book /wordpress_2025/hilfe/book
      - name: Upload to amic.de/hilfe
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: './book/'
          remoteDir: '/wordpress_2025/hilfe/book/'
          forceSSL: false
          options: "--delete --verbose"
    


        